# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-22 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], max_length=2)),
                ('minuto', models.CharField(choices=[('00', '00'), ('15', '15'), ('30', '30'), ('45', '45')], max_length=2)),
                ('sistema', models.CharField(choices=[('anexar', 'Anexar'), ('aviso', 'Aviso'), ('estrutura', 'Estrutura'), ('safari', 'Safari'), ('sublime', 'Sublime Text 2'), ('projeto', 'Projeto'), ('terminal', 'Terminal'), ('transferencia', 'Transferência'), ('war', 'War'), ('outro', 'Outro')], max_length=20)),
                ('comando', models.CharField(choices=[('cd', 'cd'), ('mkdir', 'mkdir'), ('django-admin startproject', 'django-admin startproject'), ("settings.py LANGUAGE_CODE = 'pt-br'", "settings.py LANGUAGE_CODE = 'pt-br'")], max_length=50)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('concluido', models.BooleanField(verbose_name='Concluído')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registro',
            },
        ),
    ]
